name: clang-format
on: 
  push:
    branches:
    - develop
    - master
  pull_request:
    branches:
    - develop
    - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: install tools
      run: |
        sudo apt install clang-format
        git config --global user.email "octocat@example.com"
        git config --global user.name "octocat"
    - name: refactor
      run: |
        clang-format -i -style=file Test.cpp
        git add .
        git commit -m 'refactor by Github Actions'
    - uses: push
      run: |
        git push origin
