name: clang-format
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
          sudo apt install clang-format
          # echo "Hello GitHub Actions!" >> hello.txt
          git config --global user.email "octocat@example.com"
          git config --global user.name "octocat"
          clang-format -i -style=file Test.cpp
          git add .
          git commit -m 'refactor by Github Actions'
          git push
