name: clang-format
on: 
  push:
    branches:
    - develop
    - master
  pull_request:
    branches:
    - develop
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt install clang-format
          echo "Hello GitHub Actions!" >> hello.txt
          git config --global user.email "octocat@example.com"
          git config --global user.name "octocat"
          clang-format -i -style=file Test.cpp
          git add .
          git commit -m 'refactor by Github Actions'
          git push
