name: clang-format
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Applies clang-format to all C/C++ files w/ the specified style
      - name: Apply clang-format
        id: formatting
        uses: amete/clang-format-action@v0.2
        with:
          style: 'Google'

      # Gets and prints the output message
      - name: Get the output message
        run: echo "${{ steps.formatting.outputs.message }}"
